name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build & Push the Docker image
      run: |
        docker login --username ${{ github.actor }} --password ${{ secrets.GH_PAT }} ghcr.io
        docker build . --file Dockerfile --tag ghcr.io/${{ github.actor }}/solana-devel:$(date +%s)
